/control/execute vis2.mac

/gate/geometry/setMaterialDatabase ./GateMaterials.db



#######
#WORLD#
#######

/gate/world/geometry/setXLength 2. m
/gate/world/geometry/setYLength 2. m
/gate/world/geometry/setZLength 2. m




############
#collimator#
############

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Water
/gate/cylindricalPET/geometry/setRmax 100 mm
/gate/cylindricalPET/geometry/setRmin 86 mm
/gate/cylindricalPET/geometry/setHeight 18 mm
/gate/cylindricalPET/vis/forceWireframe
/vis/viewer/zoom 3



/gate/cylindricalPET/daughters/name box1
/gate/cylindricalPET/daughters/insert box
/gate/box1/placement/setTranslation 91. 0 0 mm
/gate/box1/geometry/setXLength 10. mm
/gate/box1/geometry/setYLength 17.75 mm
/gate/box1/geometry/setZLength 17.75 mm
/gate/box1/setMaterial Water
/gate/box1/vis/setColor yellow
/gate/box1/vis/forceWireframe


# C R Y S T A L
/gate/box1/daughters/name box2
/gate/box1/daughters/insert box
/gate/box2/geometry/setXLength 10. mm
/gate/box2/geometry/setYLength 2. mm
/gate/box2/geometry/setZLength 2. mm
/gate/box2/setMaterial LSO
/gate/box2/vis/setColor red
/gate/box2/vis/forceWireframe

# Z O O M
/vis/viewer/zoom 4
/vis/viewer/panTo 60 -40 mm

# R E P E A T    C R Y S T A L
/gate/box2/repeaters/insert cubicArray
/gate/box2/cubicArray/setRepeatNumberX 1
/gate/box2/cubicArray/setRepeatNumberY 8
/gate/box2/cubicArray/setRepeatNumberZ 8
/gate/box2/cubicArray/setRepeatVector 0. 2.25 2.25 mm


# R E P E A T    R S E C T O R
/gate/box1/repeaters/insert ring
/gate/box1/ring/setRepeatNumber 30
# Z O O M
/vis/viewer/zoom 0.25
/vis/viewer/panTo 0 0 mm
# A T T A C H   V O L U M E S   T O   A   S Y S T E M
/gate/systems/cylindricalPET/rsector/attach box1
/gate/systems/cylindricalPET/module/attach box2



/gate/box2/attachCrystalSD





# P H A N T O M
/gate/world/daughters/name my_phantom
/gate/world/daughters/insert cylinder
/gate/my_phantom/setMaterial Water
/gate/my_phantom/vis/setColor grey
/gate/my_phantom/geometry/setRmax   10. mm
/gate/my_phantom/geometry/setHeight 30. mm


/gate/my_phantom/attachPhantomSD




/gate/run/initialize



/gate/source/addSource Gamma2

/gate/source/Gamma2/setActivity 0.0000000000000000001 Ci 
#0.016
#0.02

/gate/source/Gamma2/gps/type Point

/gate/source/Gamma2/gps/particle gamma

/gate/source/Gamma2/gps/energytype Mono

/gate/source/Gamma2/gps/monoenergy 662 keV   
#Co-57

/gate/source/Gamma2/gps/centre 0. 0. 1000. mm

/gate/source/Gamma2/gps/angtype iso
#angular degree
/gate/source/Gamma2/gps/mintheta 150. deg 
#80

/gate/source/Gamma2/gps/maxtheta 180. deg 
#100

/gate/source/Gamma2/gps/minphi 0. deg

/gate/source/Gamma2/gps/maxphi 360. deg

/gate/source/Gamma2/dump 1















